export type FormData = {
  attending: string;
  firstName: string;
  lastName: string;
  vegetarian: boolean;
  lactoseIntolerant: boolean;
  glutenIntolerant: boolean;
  nutAllergy: boolean;
  shellfishAllergy: boolean;
  other: boolean;
  otherAllergies: string;
  plusone: boolean;
  plusoneAttending: string;
  plusoneFirstName: string;
  plusoneLastName: string;
  plusoneVegetarian: boolean;
  plusoneLactoseIntolerant: boolean;
  plusoneGlutenIntolerant: boolean;
  plusoneNutAllergy: boolean;
  plusoneShellfishAllergy: boolean;
  plusoneOther: boolean;
  plusoneOtherAllergies: string;
};
