import "./globals.css";
import { Raleway } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import { SidebarProvider } from "@/context/SideBarContext";

import Sidebar from "@/components/sidebar/Sidebar";
const font = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider>
          <SidebarProvider>
            <div className="flex  w-full fixed z-10 ">
              <Sidebar />
              <Navbar />
            </div>

            <div className="container">{children}</div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
