import "./globals.css";
import { Raleway } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import { TranslateProvider } from "@/context/TranslateContext";
import Sidebar from "@/components/sidebar/Sidebar";
import RSVPModal from "@/components/modal/RSVPModal";

const font = Raleway({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider>
          <TranslateProvider>
            <Sidebar />
            <Navbar />
            <RSVPModal />
            <div className="">{children}</div>
          </TranslateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
